# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8020ec21eddf3bbb9a8d9c77b95331639b8544076462be30546ec860666b1cdc171d4178fcc200f68397d5afe66cc3dbc9ea62d2c97412fa61fcff1c1caa330e

test:
  secret_key_base: 75d82417df7b2c33ec2c0357e037ceeec8dc54e495bb9f024e79d3e7b0b73d3a84920e52551a155b150e763f5b86f60bc3c2476689b130b4adc948eedfa9cdb8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
