# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c12016d3daa7db7f1a04f4f30f213a5d0f63519fc184f93212a3677b56cd4eb6afc29e17fb8a5b5498fdb08286abd0651b00c8fd7105e04f9010c5d0fa3b71

test:
  secret_key_base: 195f56f02a2fe9b7a9d47270c38b0355fa2808d8734a30fa7437cf1022aebb59154c987e310c5c4a0841e88a26e3530ef55a3f3f13982c2b2d1832fa3cd0120f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
